### ISSUE TITLE
ERROR: -1013, Filter failure: LOT_SIZE

### ISSUE THREAD

**Issue by ThatPersonInTheMirror** [webcerebrium/java-binance-api#24] opened 2018-02-14 05:52 UTC
what does this error mean, I'm trying to automated trading but i get this error sometimes and a timeout error sometimes

**Comment by wcrbrm** [comment] 2018-02-14 07:18
duplicate of #7 
this is not an error of the API, you are just placing incorrect quantities. Like some of the pairs are not allowed to be decimals

**Closed by wcrbrm** 2018-02-14 07:18 UTC
